spring.application.name=EphemeralSharingService 

# Database Connection
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ephemeral_sharing_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=user_zamipter
spring.datasource.password=user_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# This is the max size for a single file
spring.servlet.multipart.max-file-size=100MB

# This is the max size for the entire request (file + other fields)
spring.servlet.multipart.max-request-size=105MB

# Expose Health Endpoint
management.endpoints.web.exposure.include=health

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
